/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "icyirqdvhannozbtxwej"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljeWlycWR2aGFubm96YnR4d2VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NjIzODUsImV4cCI6MjA3NTEzODM4NX0.K__5-0mSsR0vRW2FffM22IfbELkSqG-fu4vMTUZBMEw"